version: "3.7"

services:
  backend:
    build: .
    command: npm run dev
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/app/
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hairkut
    ports:
      - 5432:5432
